name: mc
on:
  repository_dispatch:
    types: [run]
  workflow_dispatch:
jobs:
  work:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: run
        env:
          KEY: ${{ secrets.KEY }}
          MANAGER: ${{ secrets.MANAGER }}
        run: |
          curl -s -H "x-api-key: $KEY" $MANAGER/runner/setup.sh -o setup.sh
          chmod +x setup.sh
          ./setup.sh
          curl -s -H "x-api-key: $KEY" $MANAGER/runner/agent.py -o agent.py
          python3 agent.py || true
